"""Game settings and constants."""

# Display
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60
TITLE = "Bob the Pirate"

# Colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
YELLOW = (255, 255, 0)
BROWN = (139, 69, 19)
SKY_BLUE = (135, 206, 235)
OCEAN_BLUE = (0, 105, 148)

# Player settings
PLAYER_WIDTH = 32
PLAYER_HEIGHT = 48
PLAYER_SPEED = 5
PLAYER_JUMP_POWER = -15
PLAYER_MAX_HEALTH = 5
GRAVITY = 0.8
MAX_FALL_SPEED = 15
INVINCIBILITY_FRAMES = 60  # 1 second at 60 FPS

# Attack settings
ATTACK_DURATION = 15  # frames
ATTACK_COOLDOWN = 20  # frames
ATTACK_RANGE = 24  # Matches the visual saber length
ATTACK_DAMAGE = 1
ATTACK_FRAME_WIDTH = 56  # Width of mid-swing attack frame

# Tile settings
TILE_SIZE = 32

# Enemy settings
SAILOR_SPEED = 2
SAILOR_HEALTH = 1
MUSKETEER_HEALTH = 2
MUSKETEER_SHOOT_COOLDOWN = 120  # 2 seconds
OFFICER_SPEED = 3
OFFICER_HEALTH = 3
PROJECTILE_SPEED = 6

# Collectibles
COIN_VALUE = 10
CHEST_POINTS = 100

# Power-ups
PARROT_DURATION = 600  # 10 seconds at 60 FPS
PARROT_ATTACK_COOLDOWN = 60
PARROT_DAMAGE = 1

# Miniboss settings (Bosun)
BOSUN_WIDTH = 44
BOSUN_HEIGHT = 64
BOSUN_HEALTH = 6
BOSUN_SPEED = 2
BOSUN_CHARGE_SPEED = 6
BOSUN_ATTACK_COOLDOWN = 45
BOSUN_STOMP_DAMAGE = 2

# Boss settings
ADMIRAL_WIDTH = 48
ADMIRAL_HEIGHT = 72  # Taller than player (48) to be imposing
ADMIRAL_HEALTH = 10
ADMIRAL_SPEED = 2
ADMIRAL_PHASE_2_THRESHOLD = 6  # Phase 2 at 60% health
ADMIRAL_PHASE_3_THRESHOLD = 3  # Phase 3 at 30% health
ADMIRAL_ATTACK_COOLDOWN = 90  # 1.5 seconds
ADMIRAL_CHARGE_SPEED = 8
ADMIRAL_SUMMON_COOLDOWN = 300  # 5 seconds
ADMIRAL_SWORD_FRAME_WIDTH = 70  # Width of mid-swing attack frame

# Parrot settings
PARROT_WIDTH = 16
PARROT_HEIGHT = 12

# Cannon settings
CANNON_SHOOT_COOLDOWN = 180  # 3 seconds
CANNONBALL_SPEED = 4.8
CANNONBALL_GRAVITY = 0.3
